### ISSUE TITLE
Gnome 42

### ISSUE THREAD

**Issue by Tealk** [arunk140/gnome-command-menu#2]
Get this error:

```
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  _init@/home/tealk/.local/share/gnome-shell/extensions/commandoutput@elken.tdos.gmail.com/prefs.js:23:25
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/home/tealk/.local/share/gnome-shell/extensions/commandoutput@elken.tdos.gmail.com/prefs.js:75:17
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:21:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by arunk140** [comment]
Are you sure the error message is coming from this extension?

Cause I am not using GtkGrid anywhere..
In the error log, I can see `commandoutput@elken.tdos.gmail.com` - Probably that extension is throwing that error.

https://extensions.gnome.org/extension/912/command-output/

**Comment by Tealk** [comment]
I must have clicked the wrong way during the installation, sorry.

If I turn off the version check `
gsettings set org.gnome.shell disable-extension-version-validation true` I can activate the add-on. Only the .commands.json file is not automatically created and therefore the "edit commands" button does not work at the beginning.

**Comment by molitona** [comment]
@arunk140 It doesn't work on gnome 42 for me too, anything I can help you with ?

**Comment by arunk140** [comment]
@molitona - Yeah I have not tested it on gnome 42. I am not sure what is causing the issue. I'll probably have to setup a VM today to hopefully fix it.

**Comment by molitona** [comment]
Ok, thanks.

Apr 17, 2022, 01:16 by ***@***.***:

**Comment by arunk140** [comment]
Added a test release with some changes for gnome 42. Tested on Ubuntu 22.04.

Currently only on GitHub - https://github.com/arunk140/gnome-command-menu/releases/tag/4.0.0-a

Will upload it to extensions.gnome.org after some more testing.

![image](https://user-images.githubusercontent.com/8670239/163699560-eaf9a732-ee63-4d4f-9c91-685a60c70a31.png)

**Comment by molitona** [comment]
> Added a test release with some changes for gnome 42. Tested on Ubuntu 22.04.
> 
> Currently only on GitHub - https://github.com/arunk140/gnome-command-menu/releases/tag/4.0.0-a
> 
> Will upload it to extensions.gnome.org after some more testing.
> 
> ![image](https://user-images.githubusercontent.com/8670239/163699560-eaf9a732-ee63-4d4f-9c91-685a60c70a31.png)

Thanks, it works perfectly on ArchLinux !

**Comment by sonicnkt** [comment]
Works perfectly on Fedora 36 (Beta) as well.
