### ISSUE TITLE
env variable not recognized

### ISSUE THREAD

**Issue by fgovoni** [arunk140/gnome-command-menu#5]
When I try the command 

`/home/user/script/run.sh` -- WORK

but when I try

`$HOME/script/run.sh` -- DONT WORK

Ubuntu 22.04
Command Menu verrsion 5

**Comment by arunk140** [comment]
Tested this with 
```
[
  {
    "title": "Test ENV",
    "command": "gnome-terminal -e 'bash -c \"echo $HOME;read\"'",
    "icon": "applications-utilities"
  }
]
```

seems to be working fine..

**Comment by fgovoni** [comment]
Thank you @arunk140 

With your example it worked.
