### ISSUE TITLE
Add Option to hide configure and reload

### ISSUE THREAD

**Issue by sonicnkt** [arunk140/gnome-command-menu#7]
It would be nice to have an option to hide the the "Edit Commands" and "Reload" Options in the Menu.
A toggle to hide them as well as the buttons to do those actions could be added to a extension settings panel and disabled by default.

Would be nice for a cleaner setup if you don't really change your commands that often. 

If you don't have time for this i might tackle this myself but i have no experience with gnome extension development so it would probably be a lot easier for someone who does ;)

And thanks for this great extension, i am using it daily and improved my gnome experience a lot.

**Comment by arunk140** [comment]
For Version 7 - https://github.com/arunk140/gnome-command-menu/releases/tag/7.0.0
(Untested)

Added an Extension Settings Panel - 

```
Toggle Visibility of Reload and Edit Buttons from the Menu 
(Enabled by Default - cause when the commands list is empty the menu will have no buttons)

Added Buttons to Edit and Reload in the Settings Panel 
```

**Comment by arunk140** [comment]
![image](https://user-images.githubusercontent.com/8670239/202837083-2e497368-fca0-413d-8ecd-adcfdc916ab0.png)
