### ISSUE TITLE
Support for Gnome 43 and changing menu postion

### ISSUE THREAD

**Issue by sonicnkt** [arunk140/gnome-command-menu#9]
This extensions works fine with Gnome 43 but you have to add its version to the [metadata.json](https://github.com/arunk140/gnome-command-menu/blob/main/metadata.json).

Also on Gnome 42+ its looks and feels a bit weird that menu is aligned to the right side. 

See [extension.js Line 53](https://github.com/arunk140/gnome-command-menu/blob/main/extension.js#L53).
Change the line to the following to have the menu centered above/below the indicator icon:
```
    super._init(0.5);
```
Imo this fits better with Gnome 42/43.

**Comment by arunk140** [comment]
Yep - will do those changes in some time!

**Comment by arunk140** [comment]
Changes in Release 6.0.0 - https://github.com/arunk140/gnome-command-menu/releases/tag/6.0.0
